### ISSUE TITLE
Croutines don't work

### ISSUE THREAD

**Issue by lotos2021** [deep-foundation/python-docker-isolation-provider#3]
### Describe the bug

```python
from deepclient import DeepClient, DeepClientOptions

async def fn(deep):
  new_record = {"type_id": 58, "from_id": 0, "to_id": 0}
  options = DeepClientOptions(gql_client=deep['deep'])
  deep_client = DeepClient(options)
  await deep_client.insert(new_record)
  return 400
  ```
  
  result:
  
  `
  Traceback (most recent call last):
  File "/app/index.py", line 49, in call
    'gql': gql
  File "/usr/local/lib/python3.10/site-packages/flask/json/init.py", line 342, in jsonify
    return current_app.json.response(*args, kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, dump_args)}\n", mimetype=mimetype
  File "/usr/local/lib/python3.10/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, kwargs)
  File "/usr/local/lib/python3.10/json/init.py", line 238, in dumps
    kw).encode(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/local/lib/python3.10/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/local/lib/python3.10/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).name} is not JSON serializable")
TypeError: Object of type coroutine is not JSON serializable
  `

**Comment by Lotos2021** [comment]
1) pip install flask[async]

**Comment by adzium2023** [comment]
```python

import asyncio

code = """
import asyncio

async def foo():
    return 42

coroutine = foo()
"""

namespace = {}
exec(code, namespace)

coroutine = namespace["coroutine"]

async def main():
    return await coroutine

print(asyncio.run(main())) 
```

**Comment by Lotos2021** [comment]
import asyncio

code = """
import asyncio

async def foo():
    return 42

coroutine = foo()
"""

namespace = {}
exec(code, namespace)

coroutine = namespace["coroutine"]

async def main():
    return await coroutine

print(asyncio.run(main()))
